
POST http://localhost:3000/Job/add/Employer HTTP/1.1

content-type: application/json

{
    "repName": "Winki Winki",
    "email": "Winki@gmail.com",
    "companyName": "Winki coorperation",
    "numberOfEmployee": 322
}